### ISSUE TITLE
stats.js NaN%

### ISSUE THREAD

**Issue by OSPFNeighbour** [OSPFNeighbour/Lighthouse#23]
make NaN% when the job count is 0 more user friendly.

<img width="1296" alt="screenshot 2015-12-10 18 04 13" src="https://cloud.githubusercontent.com/assets/5799222/11709056/789c8c2e-9f68-11e5-99f2-14315c63ef8d.png">

**Comment by sdunster** [comment]
++

**Comment by OSPFNeighbour** [comment]
fixed in  3d1fd3b
